FORMAT: 1A
HOST: http://138.68.92.181:8484/api

# Watchtower API

Watchtower is a simple API allowing consumers to view the given theme's influencers and feeds.

## Themes Collection [/v1.1/get_themes]

### List All Themes [GET]

+ Response 200 (application/json)

        {
            "themes": [
                {
                    "name": "Printer"
                }, 
                {
                    "name": "RaspberryPi"
                }, 
                {
                    "name": "Arduino"
                }
            ]
        }

## Feeds Collection [/v1.1/get_feeds]

### List All feeds of given theme [GET]

+ Response 200 (application/json)

        {
            "cursor_length": 60,
            "next_cursor": 20,
            "feeds": [
                {
                    "url": "https://www.kickstarter.com/projects/1340922673/mobillyo-arduino-compatible-with-ble-battery-and-s", 
                    "im": "https://ksr-ugc.imgix.net/assets/015/576/236/87ca77e23cf82e5583868c89af940d8a_original.jpg?w=1024&h=576&fit=fill&bg=000000&v=1491923257&auto=format&q=92&s=c87735fb6f1a6ff9c255b11bdbf196e4", 
                    "description": "All or nothing. This project will only be funded if it reaches its goal by Fri, May 12 2017 7:40 am EDT .", 
                    "title": "Kickstarter"
                }, 
                {
                    "url": "https://github.com/trustedsec/social-engineer-toolkit", 
                    "im": "https://avatars0.githubusercontent.com/u/3160808?v=3&s=400", 
                    "description": "social-engineer-toolkit - The Social-Engineer Toolkit (SET) repository from TrustedSec - All new versions of SET will be deployed here.", 
                    "title": "trustedsec/social-engineer-toolkit"
                }, 
                {
                    "url": "https://www.youtube.com/watch?v=hhDb1jccvi0&feature=youtu.be", 
                    "im": "https://i.ytimg.com/vi/hhDb1jccvi0/maxresdefault.jpg", 
                    "description": "Skittle Sorting Machine made for EGR 280 Sophomore design project at Oakland University.", 
                    "title": "Skittle Sorting Machine - Arduino - Oakland University"
                }, 
                {
                    "url": "https://www.youtube.com/watch?v=_jljkv5blM4", 
                    "im": "https://i.ytimg.com/vi/_jljkv5blM4/maxresdefault.jpg", 
                    "description": "Ayy lmao robotic eyes", 
                    "title": "LOOK WITH YOUR SPECIAL EYES"
                }, 
                {
                    "url": "https://www.industrialshields.com/", 
                    "im": "https://www.industrialshields.com/wp-content/uploads/2016/02/Industrial-Shields-logo-1.png", 
                    "description": "Industrial Shields develops, designs and produces Arduino PLC's using original Arudino boards, and Panel PC's using Raspberry Pi and Touchberry.", 
                    "title": "Arduino based PLC Controller for Industrial Applications by Industrial Shields"
                }, 
                {
                    "url": "https://store.boingboing.net/sales/arduino-ebook-bundle", 
                    "im": "https://cdnp1.stackassets.com/604e01a9a55e99a4df826733e318fe96712139ec/store/c44f1020920812ed7f192e7bf49ad4014bff7205c0f9551cfff7d16147e5/sale_3304_image.jpg", 
                    "description": "Arduino Enthusiast E-Book Bundle: Master This Popular Open-Source Electronics Platform with 8 E-Books (1,900+ Pages) of Project-Based Instruction", 
                    "title": "Master This Popular Open-Source Electronics Platform with 8 E-Books (1,900+ Pages) of Project-Based Instruction"
                }, 
                {
                    "url": "http://deeplocal.com/mocktailsmixer/", 
                    "im": "https://s3.us-east-2.amazonaws.com/mocktails-mixer/imgs/social.jpg", 
                    "description": "Serve up custom mixed drinks with a garnish of gab. deeplocal.com/mocktailsmixer.", 
                    "title": "Google Assistant SDK: Mocktails Mixer."
                }, 
                {
                    "url": "https://www.digitaltrends.com/cool-tech/best-arduino-projects/?utm_source=dlvr.it&utm_medium=twitter", 
                    "im": "https://icdn4.digitaltrends.com/image/43441923-arduino-electronic-platform-for-hobbyists-1200x630-c.jpg", 
                    "description": "If you really want to show off your DIY skills, Arduino projects can be useful, beautiful, and impressive. Check out some of our favorites.", 
                    "title": "Looking for a fun electronics project? Here\u2019s 12 easy Arduino-based gizmos you can build"
                }, 
                {
                    "url": "http://www.instructables.com/id/Arduino-LED-Coffee-Table/", 
                    "im": "https://cdn.instructables.com/FYQ/8236/J1VCMB3K/FYQ8236J1VCMB3K.RECT2100.jpg", 
                    "description": "This was my first real Arduino project and is also my first instructable so be kind in the comments :) I wanted to try and answer the questions that took me some time to figure out and provide detailed instructions so if you're very familiar with hobbyist electronics then you can probably skim through each step but if you're new to this it should provide you with everything you need.The aim of the project was to create a 12 x 12 pixel screen in a coffee table that can be controlled via bluetooth and used as a cool room light/play games on it.For this build you will need these parts: Arudino Mega (or clone) - https://www.amazon.co.uk/Arduino-Mega-2560-R3-Micr... Arduino micro SD Card Shield (I used this one and and soldered the headers on) - https://www.sparkfun.com/products/12761 Micro SD card - Any size will do but it must be formatted in FAT32 5m WS2812B ...", 
                    "title": "Bluetooth Controlled Arduino LED Coffee Table: 9 Steps (with Pictures)"
                }, 
                {
                    "url": "http://tinkerman.cat/fenderino-arducaster-the-coolest-guitar/", 
                    "im": "http://tinkerman.cat/wp-content/uploads/2017/03/20170210_145702s.jpg", 
                    "description": "The Fenderino is the coolest guitar ever. Well, I don't know much about guitars, but this one certainly looks different and it's really fun!", 
                    "title": "Fenderino, the coolest guitar - Tinkerman"
                }, 
                {
                    "url": "https://create.arduino.cc/projecthub/blitzkrieg/j-a-r-v-i-s-a-virtual-home-assistant-d61255?ref=search&ref_id=jarvis&offset=0", 
                    "im": "https://hackster.imgix.net/uploads/attachments/279343/upload_front-01-01_wCzutCbYqr.jpg?auto=compress%2Cformat&w=400&h=300&fit=min", 
                    "description": "J.A.R.V.I.S. is a personal home automation assistant for controlling electrical home appliances integrated with an augmented reality app. By Mantej Gill, Divyansh, and RITESH MUKHOPADHYAY.", 
                    "title": "J.A.R.V.I.S. : A Virtual Home Assistant"
                }, 
                {
                    "url": "http://smartcampus.github.io/", 
                    "im": "None", 
                    "description": "Big Data is one of the most important research challenges for the 2020 horizon. This paradigm relies on the collection of tremendous amount of data to support the innovation in the upcoming decades. According to the IDC group, the amount of world data will be 44 times greater in this decade, from 0.8 zettabytes to 35 zettabytes.", 
                    "title": "Home"
                }, 
                {
                    "url": "https://thenextweb.com/shareables/2017/04/20/teapot-dancing-robot-arduino/", 
                    "im": "https://cdn2.tnwcdn.com/wp-content/blogs.dir/1/files/2017/04/Screen-Shot-2017-04-20-at-11.13.08.png", 
                    "description": "One resourceful inventor has hooked his 3D-printed teapot to an Arduino board to create this cute little robot that also happens to dance.", 
                    "title": "This cute dancing robot is actually a 3D-printed teapot hooked to an Arduino"
                }, 
                {
                    "url": "https://de.mathworks.com/matlabcentral/fileexchange/58189-gesture-controlled-robotic-arm-using-kinect--simulink-support-for-kinect--and-arduino?s_eid=PSM_arlm&hootPostID=e60a0240a0c5d4e2aafe6a6f5cbc6a1d&requestedDomain=www.mathworks.com", 
                    "im": "https://de.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/58189/versions/4/screenshot.png", 
                    "description": "This is a Simulink Model to Control a Robotic Arm By Gestures that are captured using Kinect Sensor.", 
                    "title": "Gesture Controlled Robotic Arm Using Kinect (Simulink Support For Kinect) and Arduino - File Exchange - MATLAB Central"
                }, 
                {
                    "url": "http://hackaday.com/2017/04/27/sous-vide-arduino-isnt-lost-in-translation/", 
                    "im": "https://hackadaycom.files.wordpress.com/2017/04/sous600.png?w=600&h=600", 
                    "description": "If your idea of a six-course meal is a small order of chicken nuggets, you might have missed the rise of sous vide among cooks. The idea is you seal food in a plastic pouch and then cook it in a water...", 
                    "title": "Sous Vide Arduino isn\u2019t Lost in Translation"
                }, 
                {
                    "url": "https://blog.hackster.io/the-paperino-is-an-epaper-display-for-your-particle-and-arduino-boards-cb3a52955c85", 
                    "im": "https://cdn-images-1.medium.com/max/1200/1*gDvrBDOGnYHO7XJTI69kmQ.jpeg", 
                    "description": "If you\u2019d like your project to output human-readable information, you normally turn to LEDs or other devices that drain precious current out\u2026", 
                    "title": "The Paperino Is an ePaper Display for Your Particle and Arduino Boards"
                }, 
                {
                    "url": "https://create.arduino.cc/projecthub/Arduino_Genuino/mkrfox1200-weather-monitor-6a94e2?ref=platform&ref_id=424_recent___&offset=5", 
                    "im": "https://hackster.imgix.net/uploads/attachments/292700/socials_mkrfox1200_bVlDZFCxco.jpg?auto=compress%2Cformat&w=400&h=300&fit=min", 
                    "description": "Turn your MKRFOX1200 into a battery-powered weather monitor that you can deploy EVERYWHERE. By Arduino_Genuino.", 
                    "title": "MKRFOX1200 Weather Monitor"
                }, 
                {
                    "url": "http://www.techrepublic.com/article/farming-for-the-future-how-one-company-uses-big-data-to-maximize-yields-and-minimize-impact/?platform=hootsuite", 
                    "im": "https://tr3.cbsistatic.com/hub/i/r/2017/04/21/3467d1bc-317e-4eea-8a83-f6bf7d62c120/thumbnail/770x578/de94f8815db5ffa9a8c3e5f1e648b8a8/farmer-with-tablet.jpg", 
                    "description": "Foris.io has a mission: Make farms more productive and protect the environment while doing it. With a combination of hardware and machine learning from IBM, Foris.io aims to change the way we farm.", 
                    "title": "Farming for the future: How one company uses big data to maximize yields and minimize impact - TechRepublic"
                }, 
                {
                    "url": "http://cdm.link/2017/04/ardutouch-one-arduino-synthesizer-learning-kit-30/", 
                    "im": "http://cdm.link/app/uploads/2017/04/ardutouch.jpg", 
                    "description": "A $25-30 board has a touch keyboard, controls, and speaker - and teaches beginning DSP coding. Meet the creator, and learn why hackerspaces matter.", 
                    "title": "ArduTouch is an all-in-one Arduino synthesizer learning kit for $30 - CDM Create Digital Music"
                }, 
                {
                    "url": "http://madeintheusb.blogspot.de/2016/07/faster-serial-port-communication-from.html", 
                    "im": "https://2.bp.blogspot.com/-6EQUqbxH3ZE/WM3U5Dq0piI/AAAAAAAAAgo/e2dKVv16UDAD61ZdoOXWI8FmrUiJ_qjpgCLcB/w1200-h630-p-k-no-nu/NusbioMCU_Square.2017.Rainbow.01.jpg", 
                    "description": "Overview I was for a long time thinking that serial port communication on Windows and/or .NET was limited to 115 200 bauds, which translat...", 
                    "title": "Faster serial port communication from .NET to Arduino"
                }
            ]
        }